### ISSUE TITLE
ImmichFrame stopped working

### ISSUE THREAD

**Issue by JME-DDY** [immichFrame/ImmichFrame#276]
### Version

latest

### Deployment Method

Docker Compose via Portainer

### Description

Immich Frame stopped working, no config changed, nor any updates to immich

Below is the log : 

warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]

      Using an in-memory repository. Keys will not be persisted to storage.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]

      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.

warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]

      No XML encryptor configured. Key {REDACTED} may be persisted to storage in unencrypted form.

info: Microsoft.Hosting.Lifetime[14]

      Now listening on: http://[::]:8080

info: Microsoft.Hosting.Lifetime[0]

      Application started. Press Ctrl+C to shut down.

info: Microsoft.Hosting.Lifetime[0]

      Hosting environment: Production

info: Microsoft.Hosting.Lifetime[0]

      Content root path: /app

### Reproduction

Unsure

### Configuration

```xml

```

### Logs

```shell

```

### Pre-Submission Checklist

- [x] This is a bug report and not a feature request

- [x] I have provided all of the required information to reproduce the bug (config, logs, etc.)

- [x] I have checked for related issues and checked the documentation

**Comment by 3rob3** [comment]
Weird. What OS is this running on? New'ish ImmichFrame install or been running awhile?

@JW-CH any ideas?

**Comment by JW-CH** [comment]
Kill the container, maybe? Delete the images and pull them again.

**Comment by JME-DDY** [comment]
> Weird. What OS is this running on? New'ish ImmichFrame install or been running awhile?
> 
> [@JW-CH](https://github.com/JW-CH) any ideas?

It's hosted on my QNAP 464. Had it running for maybe 3 months or so with no issues and not made any updates to any other containers or QNAP since. 

@JW-CH - Killed the container, deleted images and set back up but got the same issue again.

Here's my docker-compose if it helps:

services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:latest
    restart: on-failure
    ports:
      - "2284:8080"
    environment:
      TZ: "America/New_York"
      # Required
      ImmichServerUrl: "http://REDACTED:2283"
      ApiKey: "REDACTED"
  #control / 
      #Security
      #AuthenticationSecret: "test"
      # Image
      ImageZoom: "true"  
      Interval: "10"
      TransitionDuration: "2"
      # Filters
    #Albums: "ALBUM1,ALBUM2"  # Add your specific albums
    #ExcludedAlbums: "ALBUM3,ALBUM4"
    #  People: "Jamie Samuel"
      ShowMemories: "false"
    #ShowFavorites: "false"
    #ImagesFromDays: ""
    #ImagesFromDate: ""
    #ImagesUntilDate: ""
      # Clock
      ShowClock: "true"
      ClockFormat: "HH:mm"
      # Weather
      WeatherApiKey: "REDACTED"  # OpenWeather
      UnitSystem: "metric"  # Change to "metric" for Celsius
      Language: "en"
      ShowWeatherDescription: "true"
      WeatherLatLong: "40.712776, -74.005974"  # New York coordinates
      # Metadata
      ShowImageDesc: "true"
      ShowImageLocation: "true"
      ShowPhotoDate: "true"
      PhotoDateFormat: "yyyy-MM-dd"
      # Caching
      RenewImagesDuration: "30"
      DownloadImages: "false"
      RefreshAlbumPeopleInterval: "12"
      # UI
      PrimaryColor: "#FF5733"
      BaseFontSize: "17px"
      # Misc
      ImmichFrameAlbumName: ""

**Comment by JW-CH** [comment]
Can you try with the bare minimum of config (ImmichServerUrl & ApiKey), remove the other env variables. Downgrade to an older version? (not latest)

**Comment by JME-DDY** [comment]
Hi, 

I attempted this with a few different previous versions but still no luck

**My docker compose :** 
services:
  immichframe:
    container_name: immichframe
    image: ghcr.io/immichframe/immichframe:v1.0.19.0
    restart: on-failure
    ports:
      - "2284:8080"
    environment:
      TZ: "America/New_York"
      # Required
      ImmichServerUrl: "http://REDACTED3:2283"
      ApiKey: "REDACTED"

Log file : 

      
/app/Config/Settings.json

info: Microsoft.Hosting.Lifetime[14]

      Now listening on: http://[::]:8080

info: Microsoft.Hosting.Lifetime[0]

      Application started. Press Ctrl+C to shut down.

info: Microsoft.Hosting.Lifetime[0]

      Hosting environment: Production

info: Microsoft.Hosting.Lifetime[0]

      Content root path: /app

fail: Microsoft.AspNetCore.Server.Kestrel[13]

      Connection id "0HNAPP4RSNO3H", Request id "0HNAPP4RSNO3H:00000002": An unhandled exception was thrown by the application.

      System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

       ---> System.TimeoutException: A task was canceled.

       ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

         --- End of inner exception stack trace ---

         --- End of inner exception stack trace ---

         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

         at ImmichFrame.Core.Api.ImmichApi.SearchRandomAsync(RandomSearchDto body, CancellationToken cancellationToken) in /source/ImmichFrame.Core/obj/immich-openapi-specsClient.cs:line 8223

         at ImmichFrame.Core.Logic.ImmichFrameLogic.LoadRandomAssets() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 414

         at ImmichFrame.Core.Logic.ImmichFrameLogic.GetRandomAssets() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 355

         at ImmichFrame.Core.Logic.ImmichFrameLogic.GetAssets() in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 62

         at ImmichFrame.WebApi.Controllers.AssetController.GetAsset() in /source/ImmichFrame.WebApi/Controllers/AssetController.cs:line 26

         at lambda_method6(Closure, Object)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**Comment by janwillemb** [comment]
If there is a large amount of images in the selection, a timeout occurs. A workaround is to limit the period:

```yaml
ImagesFromDate: "2013-01-01"
ImagesUntilDate: "2024-12-31"
```

**Comment by 3rob3** [comment]
Those are just warnings that we are not persisting keys across sessions (i.e. reboot). This shouldn't be the cause of the issue. I didn't write this code so I am not 100% sure of this however.

I am wondering if this is related to the tags issue #279 . Did either of you happen to manually tag anything yet?

**Comment by 3rob3** [comment]
I pushed a new release for the tag fix, worth a shot to try it and see if this issue was related.

**Comment by 3rob3** [comment]
Any update on this?

**Comment by kllngtme** [comment]
curiously it started working randomly by itself without me making any changes. That being said. There are still issues it seems where the app crashes. Not sure what it is. I just stop it and start it to get it going again. I haven't been able to catch a log for it.

**Comment by Anguszzzzzzz** [comment]
I've been experiencing the same issue since about 2 updates ago. The client would display a "ImmichFrame has stopped working" pop-up, then the client would auto fix itself after a while. The issue still happens with the latest apk "v37"

Web server container log:
`2025-03-25T10:18:10.320638685Z fail: Microsoft.AspNetCore.Server.Kestrel[13]
2025-03-25T10:18:10.320666182Z       Connection id "0HNB3BOFKTKH3", Request id "0HNB3BOFKTKH3:0000000A": An unhandled exception was thrown by the application.
2025-03-25T10:18:10.320696638Z          at ImmichFrame.Core.Logic.ImmichFrameLogic.GetImage(Guid id) in /source/ImmichFrame.Core/Logic/ImmichFrameLogic.cs:line 110
2025-03-25T10:18:10.320671999Z       
2025-03-25T10:18:10.320669833Z       HTTP Response: 
2025-03-25T10:18:10.320673867Z       error code: 1033
2025-03-25T10:18:10.320675728Z       
2025-03-25T10:18:10.320689211Z       
2025-03-25T10:18:10.320677578Z       ImmichFrame.Core.Api.ApiException: The HTTP status code of the response was not expected (530).
2025-03-25T10:18:10.320691093Z       Status: 530
2025-03-25T10:18:10.320692440Z       Response: 
2025-03-25T10:18:10.320695042Z          at ImmichFrame.Core.Api.ImmichApi.ViewAssetAsync(Guid id, String key, Nullable`1 size, CancellationToken cancellationToken) in /source/ImmichFrame.Core/obj/immich-openapi-specsClient.cs:line 3490
2025-03-25T10:18:10.320693719Z       error code: 1033
2025-03-25T10:18:10.320698115Z          at ImmichFrame.WebApi.Controllers.AssetController.GetRandomImageAndInfo(String clientIdentifier) in /source/ImmichFrame.WebApi/Controllers/AssetController.cs:line 62
2025-03-25T10:18:10.320699613Z          at lambda_method4(Closure, Object)
2025-03-25T10:18:10.320701022Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2025-03-25T10:18:10.320702715Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
2025-03-25T10:18:10.320704618Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2025-03-25T10:18:10.320706358Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
2025-03-25T10:18:10.320707813Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2025-03-25T10:18:10.320710160Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2025-03-25T10:18:10.320712009Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2025-03-25T10:18:10.320713733Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-03-25T10:18:10.320715348Z          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2025-03-25T10:18:10.320716884Z          at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
2025-03-25T10:18:10.320718282Z          at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
2025-03-25T10:18:10.320719662Z          at CustomAuthenticationMiddleware.InvokeAsync(HttpContext context) in /source/ImmichFrame.WebApi/Helpers/CustomAuthenticationMiddleware.cs:line 23
2025-03-25T10:18:10.320723241Z          at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Comment by 3rob3** [comment]
Frameo or running in webview?

**Comment by Anguszzzzzzz** [comment]
> Frameo or running in webview?

Frameo

**Comment by 3rob3** [comment]
> > Frameo or running in webview?
> 
> Frameo

Sorry, I see you said that now. This is a different issue. I started seeing this when splitview was implemented for non-webview, and it is a memory issue on the Frameo. It originally was much worse but I optimized it and stopped seeing it. Maybe your images are higher res than mine or something. I think we'd have to downscale images for splitview to solve this. In the meantime I bet disabling splitview server-side would also fix it.

**Comment by Anguszzzzzzz** [comment]
> > > Frameo or running in webview?
> > 
> > 
> > Frameo
> 
> I started seeing this when splitview was implemented for non-webview, and it is a memory issue on the Frameo.

That checks out yeah. That was the update when I first started getting these crashes. Good to know though so thanks for the response!

**Comment by 3rob3** [comment]
I got log at running on mine to try and trap it again. I’ll try to improve this.

**Comment by 3rob3** [comment]
New Android app with splitview and other memory optimizations released.
